spring:
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      generate-ddl: false
      open-in-view: false
      show-sql: false
      hibernate:
         ddl-auto: none
      properties:
         hibernate.id.new_generator_mappings: true
         hibernate.cache.use_second_level_cache: false
         hibernate.cache.use_query_cache: true
         hibernate.generate_statistics: false
   datasource:
       type: com.zaxxer.hikari.HikariDataSource
       #dataSourceClassName: org.postgresql.Driver
       url: jdbc:postgresql://localhost:5432/soch-db-dev?currentSchema=soch
       username: postgres
       password: postgres
       hikari:
        poolName: Hikari
logging:
   level:
       root: info
       org: info
       gov: info
mhl:
  auth_key: c2285c7c4cdaf31f8486b35f171c643c
accessKey: devkey@3
crossDomainAllowedOrigins:
jwtSecret: U09DSCtUMHBTM2NyRXQrQXV0aG9yaXphdGlvbit0b2tlbitrZXk=
exportRecordsLimit: 50000